---
title       : 'Introducing Data Science with R'
subtitle    : 'week.5'
author      : '謝舒凱 Lab of Ontologies, Language Processing and e-Humanities'
job         : 'GIL, National Taiwan University'
logo        : lope.png
biglogo     : lopen.png
license     : by-sa
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax, quiz, bootstrap]    # {mathjax, quiz, bootstrap}
ext_widgets: {rCharts: [libraries/widgets/nvd3]}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
bibliography: /Users/shukai/LOPE_LexInfo/BIB/myRef.bib
github      : {user: loperntu, repo: dsR}



--- 
## 大綱
1. __``Basic R__``  (80min)
2. A glace at a data science example (20min)
3. Lab session (50min)




---
##

```{r}
library(ggplot2)
qplot(x=Sepal.Length, y=Petal.Length, data=iris)
```



---
## Textual data preprocessing

- 使用 `jiebaR` (0.81 for R version 3.2.4)
```{r}
library(jiebaR)
##  Using default settings to initialize a worker.
cutter = worker()
segment( "給我六個小時砍樹，我會花前四個小時磨斧", cutter)
```

